// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkmriglevzxrdlpkxkwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rbXJpZ2xldnp4cmRscGt4a3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDE5NDAsImV4cCI6MjA2Nzg3Nzk0MH0.FZlLP8aEuy2Cy34cO9Cmfqg4AHeD07PBVeMaygk0fDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});